name: flutter_application_2
description: "Plug provider app."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.7



dependencies:
  cached_network_image: ^3.4.1
  cross_connectivity: ^3.3.0
  flutter:
    sdk: flutter

  huawei_hmsavailability:
    path: "D:/plug/huawei_availability"
  flexible_polyline:
    path: "D:/plug/flexible-polyline-master"
  here_sdk:
    path: "D:/plug/here-sdk"
 
  geolocator: ^14.0.2
  
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.12.3
  huawei_location: ^6.16.0+300
  flutter_dotenv: ^5.2.1
  flutter_image_slideshow: ^0.1.6
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  flutter_vector_icons: ^2.0.0
  get_storage: ^2.1.1
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  http: ^1.5.0
  image_picker: ^1.2.0
  another_flushbar: ^1.10.24
  intl: ^0.20.2
  logger: ^2.6.1
  page_view_dot_indicator: ^2.3.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  
  flexible_polyline_dart: ^1.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  dio: ^5.9.0
  
  # agconnect_core: ^1.9.0+300

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/plug_icon.png"
  android_adaptive_icon:
    foreground_image: "assets/icons/plug_icon.png"
    background_color: "#00000000"
  min_sdk_android: 21
  remove_alpha_ios: true



flutter:
  uses-material-design: true

  assets:
    - assets/icons/plug_splash.png
    - .env.development
    - assets/icons/plug_icon.png
    - assets/images/onboarding_one.png
    - assets/icons/map_icons/client_marker.png
    - assets/icons/map_icons/sp_marker.png
    - assets/images/onboarding_two.png
    - assets/images/onboarding_three.png
    



